### ISSUE TITLE
Work with me/Rakugo version

### ISSUE THREAD

**Issue by Jeremi360** [kyperbelt/GDYarn#2]
Hi, I'm working on: [**Rakugo**](https://github.com/rakugoteam/Rakugo)
***Rakugo** is inspired by Ren’Py, addons + template aimed at providing a better toolset for narrative-based games on Godot.*
*Simplify your project, if it is a visual novel, point and click, RPG, interactive text game or many other styles and blends of styles.*

Maybe you are interested in joining our forces together, by making this plugin for Rakugo, I would help.
Rakugo already has: dialogue events connected to GUI, global vars, save/load, history, rollback, options.

**Comment by kyperbelt** [comment]
Right now there is no plan for the gdyarn plugin to support a specific front-end (will soon phase out the need to pass in a gui implementation). That being said, I don't think it would hurt if you added support for yarnspinner files to your plugin. 

Currenly gdyarn is not ready for production (at least not without a lot of finicking around with it), but in the near future,  the yarnrunner should more easily feed multiple gui implementations.

**Comment by Jeremi360** [comment]
okey, @kyperbelt thanks for quick anwser
