### ISSUE TITLE
Compiled Yarn Program

### ISSUE THREAD

**Issue by drearyweary** [kyperbelt/GDYarn#5]
Hello @kyperbelt , I am trying out your plugin and have followed the steps listed but am having trouble understanding what to do at the Compiled Yarn Program step. I already have my own Yarn files that I've used in other programs and would like to see if they work.

How would I go about generating the resource that goes into the Yarn Runner "Compiled Yarn Program" section? When I click it, it just gives me a giant list of resource types (screenshot below) that I cannot scroll down from.

Thank you for your help.

![Screen Shot 2022-02-14 at 1 18 22 AM](https://user-images.githubusercontent.com/87843427/153766676-7c45856c-02cf-4227-ade3-4c6603229d46.png)

**Comment by kyperbelt** [comment]
Hey Drearyweary,

I apologize for how long I took to respond, but I hope that I can still be of some help. 

The resource should be found on that drop-down if you scroll down further. I think this might be an issue with the editor if it is not letting you scroll.

Admittedly, I do not remember why I decided to separate the list of programs to compile into its own resource, and I give ownership of the file array back to the yarn runner if that makes it easier to use. 

Let me know if you are still having issues, or if you need help with something else. I am much easier to reach through discord @ kyperbelt #1288

**Comment by drearyweary** [comment]
Thanks for replying. I figured out how to get it to work. I only copied the addons folder and didn't realize the resource file was in the top level of the repo outside the addons. It was easier to drag and drop from there. It's neat that you managed to get yarn files to work.
