### ISSUE TITLE
Help with exporting

### ISSUE THREAD

**Issue by yeoji** [kyperbelt/GDYarn#9]
Hey! I am trying to use this plugin for a mini game I'm making and it all worked well until I had to export the project.

Looks like it can't find the `.tsv` file (screenshot attached below). It initially complained about not being able to find the `.cyarn` file, and I've added it to the export's included non-resource files. The same solution doesn't seem to work for `.tsv`.

Would be nice to get some guidance on how to get export working.

Nice work on the plugin itself :)

<img width="874" alt="Screen Shot 2022-06-13 at 11 01 19 am" src="https://user-images.githubusercontent.com/8002179/173261936-100723ac-190b-49b0-be2b-90274f99a196.png">

<img width="455" alt="Screen Shot 2022-06-13 at 11 02 42 am" src="https://user-images.githubusercontent.com/8002179/173261945-16b49424-8bc4-4e93-a9dc-6183ffd0aa85.png">

**Comment by yeoji** [comment]
Okay, I think I got it working. It was actually because of a change I made to the plugin `_import_program` function.

I made a change to the way the `.tsv` path is constructed because the original caused a duplicate of the directory name.

**Original:**
```
const DEFAULT_STRINGS_FORMAT = "%s%s-strings.%s"
var stringsPath = (
  DEFAULT_STRINGS_FORMAT
  % [
	  filePath.get_base_dir().trim_prefix("res://"),
	  filePath.get_basename(),
	  STRINGS_EXTENSION
  ]
)
```

**My Change:**
```
const DEFAULT_STRINGS_FORMAT = "%s-strings.%s"

var stringsPath = DEFAULT_STRINGS_FORMAT % [
		filePath.get_basename().trim_prefix("res://"),
		STRINGS_EXTENSION
]
```

**Working:**
```
const DEFAULT_STRINGS_FORMAT = "%s-strings.%s"

var stringsPath = DEFAULT_STRINGS_FORMAT % [
		filePath.get_basename(),
		STRINGS_EXTENSION
]
```

Thanks for the plugin!

**Comment by kyperbelt** [comment]
Hi, @yeoji . 

Thank you for using the plugin!

I think the reason the original did not work is that the file was being stored in the root folder and it assumes that it will be in some nested structure(This is a bug). I'll add this to the backlog of things that need fixing. 

Glad you were able to employ a fix that worked for you!

- Jonathan C. (Kyperbelt)

**Comment by yeoji** [comment]
Thanks for the plugin! Was great being able to try out Yarn using Godot :)
